# Generated by Django 5.0.4 on 2024-04-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('Id_chofer', models.IntegerField(primary_key=True, serialize=False)),
                ('Legajo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('calle', models.CharField(max_length=100, unique=True)),
                ('nrocalle', models.CharField(max_length=10)),
                ('piso', models.CharField(max_length=10)),
                ('Deptartamento', models.CharField(max_length=10)),
                ('barrio', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=80)),
                ('provincia', models.CharField(max_length=10)),
                ('cp', models.IntegerField()),
                ('movil', models.CharField(max_length=15)),
                ('contactoemergencia', models.CharField(max_length=80)),
                ('parentesco', models.CharField(blank=True, max_length=80)),
                ('foto', models.ImageField(blank=True, upload_to='fotochofer/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_activo', models.BooleanField(default=True)),
            ],
        ),
    ]
