# Generated by Django 5.0.3 on 2024-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0002_remove_chofer_is_activo_remove_chofer_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='Deptartamento',
        ),
        migrations.AddField(
            model_name='chofer',
            name='departamento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='Id_chofer',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='calle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='piso',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
