# Generated by Django 5.0.3 on 2024-07-19 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0003_remove_chofer_deptartamento_chofer_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='curso_venc',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AddField(
            model_name='chofer',
            name='ingresoFCA_venc',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AddField(
            model_name='chofer',
            name='licencia_venc',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AddField(
            model_name='chofer',
            name='psicofisico_venc',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
    ]
