# Generated by Django 5.0.3 on 2024-07-22 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0006_alter_chofer_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='Legajo',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='chofer',
            name='barrio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='contactoemergencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='cp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='curso_venc',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='departamento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='dni',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='ingresoFCA_venc',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='licencia_venc',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='localidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='parentesco',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='piso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='provincia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='psicofisico_venc',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chofer',
            name='legajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
