# Generated by Django 5.0.3 on 2024-07-22 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0007_remove_chofer_legajo_remove_chofer_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='legajo',
        ),
    ]
