# Generated by Django 5.0.3 on 2024-07-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0008_remove_chofer_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
