# Generated by Django 5.0.3 on 2024-07-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipoKilometro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movimiento',
        ),
        migrations.RemoveField(
            model_name='tipokilometro',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tipokilometro',
            name='tk_nombre',
        ),
        migrations.AddField(
            model_name='tipokilometro',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tipokilometro',
            name='idTipoKilometro',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
