# Generated by Django 5.0.3 on 2024-07-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipoKilometro', '0002_delete_movimiento_remove_tipokilometro_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipokilometro',
            name='idTipoKilometro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
