# Generated by Django 5.0.3 on 2024-07-26 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoKilometro', '0002_delete_movimiento_remove_tipokilometro_id_and_more'),
        ('usuarios', '0003_remove_usuariochofer_movil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoKilometros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('mov_id', models.AutoField(primary_key=True, serialize=False)),
                ('nFlota', models.CharField(blank=True, max_length=60, null=True)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('kmInicio', models.IntegerField(default=0)),
                ('kmFin', models.IntegerField(blank=True, null=True)),
                ('lugar_inicio', models.CharField(max_length=60)),
                ('lugar_fin', models.CharField(blank=True, max_length=60, null=True)),
                ('lleva_carga', models.BooleanField(default=False)),
                ('permanencia', models.BooleanField(default=False)),
                ('diasPermanencia', models.IntegerField(default=0)),
                ('cruce_frontera', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('modif', models.DateTimeField(auto_now=True)),
                ('comentarios', models.CharField(blank=True, max_length=250, null=True)),
                ('chofer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariochofer')),
                ('tipo_kilometro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TipoKilometro.tipokilometro')),
            ],
        ),
    ]
