# Generated by Django 5.0.3 on 2024-07-24 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chofer', '0009_chofer_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('mov_id', models.AutoField(primary_key=True, serialize=False)),
                ('nFlota', models.CharField(blank=True, max_length=60, null=True)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('kmInicio', models.IntegerField(default=0)),
                ('kmFin', models.IntegerField(blank=True, null=True)),
                ('lugar_inicio', models.CharField(max_length=60)),
                ('lugar_fin', models.CharField(blank=True, max_length=60, null=True)),
                ('lleva_carga', models.BooleanField(default=False)),
                ('permanencia', models.BooleanField(default=False)),
                ('diasPermanencia', models.IntegerField(default=0)),
                ('cruce_frontera', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('modif', models.DateTimeField(auto_now=True)),
                ('comentarios', models.CharField(blank=True, max_length=250, null=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chofer.chofer')),
            ],
        ),
    ]
