# Generated by Django 5.0.3 on 2024-07-21 22:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('Id_chofer', models.AutoField(primary_key=True, serialize=False)),
                ('Legajo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('calle', models.CharField(max_length=100)),
                ('nrocalle', models.CharField(max_length=10)),
                ('piso', models.CharField(blank=True, max_length=10)),
                ('departamento', models.CharField(blank=True, max_length=10)),
                ('barrio', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=80)),
                ('provincia', models.CharField(max_length=10)),
                ('cp', models.IntegerField()),
                ('movil', models.CharField(max_length=15)),
                ('contactoemergencia', models.CharField(max_length=80)),
                ('parentesco', models.CharField(blank=True, max_length=80)),
                ('foto', models.ImageField(blank=True, upload_to='fotochofer/')),
                ('ingresoFCA_venc', models.DateField(default=datetime.date(2025, 1, 1))),
                ('licencia_venc', models.DateField(default=datetime.date(2025, 1, 1))),
                ('psicofisico_venc', models.DateField(default=datetime.date(2025, 1, 1))),
                ('curso_venc', models.DateField(default=datetime.date(2025, 1, 1))),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_chofer_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
