# Generated by Django 5.0.3 on 2024-07-26 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipoKilometro', '0003_alter_tipokilometro_idtipokilometro'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='tipo_kilometro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoKilometro.tipokilometro'),
        ),
    ]
