# Generated by Django 5.0.3 on 2024-07-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0004_movimientos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='usuario',
        ),
    ]
