# Generated by Django 5.0.3 on 2024-07-28 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0006_movimientos_usuario_alter_movimientos_chofer'),
        ('usuarios', '0004_alter_usuario_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='chofer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariochofer'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
