# Generated by Django 5.0.3 on 2024-07-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0009_alter_movimientos_chofer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
