# Generated by Django 5.0.6 on 2024-07-29 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0010_rename_usuario_movimientos_usuario_id'),
        ('usuarios', '0005_alter_usuario_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariochofer'),
        ),
    ]
