# Generated by Django 5.0.6 on 2024-08-02 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0011_rename_usuario_id_movimientos_usuario_and_more'),
        ('usuarios', '0005_alter_usuario_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariochofer'),
        ),
    ]
