# Generated by Django 5.0.6 on 2024-08-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0012_rename_usuario_movimientos_usuario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
