# Generated by Django 5.0.6 on 2024-08-02 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0009_chofer_nombre'),
        ('movimientos', '0014_remove_movimientos_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chofer.chofer'),
        ),
    ]
