# Generated by Django 5.0.3 on 2024-07-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(default='123456789', max_length=128)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(default='default_username', max_length=50, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('chofer', 'Chofer')], default='chofer', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
