# Generated by Django 5.0.3 on 2024-07-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariochofer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariochofer',
            name='movil',
        ),
        migrations.AlterField(
            model_name='usuariochofer',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuariochofer',
            name='dni',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuariochofer',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='choferes/fotos/'),
        ),
        migrations.AlterField(
            model_name='usuariochofer',
            name='parentesco',
            field=models.CharField(max_length=100),
        ),
    ]
