# Generated by Django 5.0.6 on 2024-07-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('chofer', 'Chofer')], default='chofer', max_length=10),
        ),
    ]
